# Data Preprocessing

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('retail_data2.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(X)

[['UK' 34.0 41000.0]
 ['France' 22.0 52000.0]
 ['Germany' nan 47000.0]
 ['Spain' 45.0 29000.0]
 ['Italy' 19.0 61000.0]
 ['UK' 58.0 32000.0]
 ['France' 27.0 nan]
 ['Germany' 41.0 54000.0]
 ['Spain' 33.0 72000.0]
 ['Italy' nan 38000.0]
 ['UK' 29.0 90000.0]
 ['France' 52.0 31000.0]
 ['Germany' 24.0 66000.0]
 ['Spain' 61.0 28000.0]
 ['Italy' 37.0 nan]
 ['UK' 43.0 51000.0]
 ['France' 31.0 84000.0]
 ['Germany' nan 45000.0]
 ['Spain' 26.0 35000.0]
 ['Italy' 48.0 27000.0]
 ['UK' 22.0 70000.0]
 ['France' 39.0 nan]
 ['Germany' 57.0 33000.0]
 ['Spain' 28.0 62000.0]
 ['Italy' 25.0 81000.0]
 ['UK' nan 56000.0]
 ['France' 46.0 29000.0]
 ['Germany' 32.0 75000.0]
 ['Spain' 54.0 nan]
 ['Italy' 21.0 69000.0]
 ['UK' 63.0 31000.0]
 ['France' 35.0 43000.0]
 ['Germany' 29.0 88000.0]
 ['Spain' nan 52000.0]
 ['Italy' 44.0 26000.0]
 ['UK' 23.0 77000.0]
 ['France' 50.0 34000.0]
 ['Germany' 38.0 nan]
 ['Spain' 47.0 41000.0]
 ['Italy' 33.0 93000.0]
 ['UK' 56.0 28000.0]
 ['France' 20.0 64000.0]
 ['Germany' nan 580

In [14]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 

In [15]:
# Taking care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])

In [16]:
print(X)

[['UK' 34.0 41000.0]
 ['France' 22.0 52000.0]
 ['Germany' 37.823232323232325 47000.0]
 ['Spain' 45.0 29000.0]
 ['Italy' 19.0 61000.0]
 ['UK' 58.0 32000.0]
 ['France' 27.0 56180.90452261306]
 ['Germany' 41.0 54000.0]
 ['Spain' 33.0 72000.0]
 ['Italy' 37.823232323232325 38000.0]
 ['UK' 29.0 90000.0]
 ['France' 52.0 31000.0]
 ['Germany' 24.0 66000.0]
 ['Spain' 61.0 28000.0]
 ['Italy' 37.0 56180.90452261306]
 ['UK' 43.0 51000.0]
 ['France' 31.0 84000.0]
 ['Germany' 37.823232323232325 45000.0]
 ['Spain' 26.0 35000.0]
 ['Italy' 48.0 27000.0]
 ['UK' 22.0 70000.0]
 ['France' 39.0 56180.90452261306]
 ['Germany' 57.0 33000.0]
 ['Spain' 28.0 62000.0]
 ['Italy' 25.0 81000.0]
 ['UK' 37.823232323232325 56000.0]
 ['France' 46.0 29000.0]
 ['Germany' 32.0 75000.0]
 ['Spain' 54.0 56180.90452261306]
 ['Italy' 21.0 69000.0]
 ['UK' 63.0 31000.0]
 ['France' 35.0 43000.0]
 ['Germany' 29.0 88000.0]
 ['Spain' 37.823232323232325 52000.0]
 ['Italy' 44.0 26000.0]
 ['UK' 23.0 77000.0]
 ['France' 50.0 34000.0]
 ['G

In [17]:
# Encoding Categorical Data

# Encoding the Independent Variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



In [19]:
np.set_printoptions(threshold=np.inf)
print(X)

[[0.0 0.0 0.0 0.0 1.0 34.0 41000.0]
 [1.0 0.0 0.0 0.0 0.0 22.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 37.823232323232325 47000.0]
 [0.0 0.0 0.0 1.0 0.0 45.0 29000.0]
 [0.0 0.0 1.0 0.0 0.0 19.0 61000.0]
 [0.0 0.0 0.0 0.0 1.0 58.0 32000.0]
 [1.0 0.0 0.0 0.0 0.0 27.0 56180.90452261306]
 [0.0 1.0 0.0 0.0 0.0 41.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 33.0 72000.0]
 [0.0 0.0 1.0 0.0 0.0 37.823232323232325 38000.0]
 [0.0 0.0 0.0 0.0 1.0 29.0 90000.0]
 [1.0 0.0 0.0 0.0 0.0 52.0 31000.0]
 [0.0 1.0 0.0 0.0 0.0 24.0 66000.0]
 [0.0 0.0 0.0 1.0 0.0 61.0 28000.0]
 [0.0 0.0 1.0 0.0 0.0 37.0 56180.90452261306]
 [0.0 0.0 0.0 0.0 1.0 43.0 51000.0]
 [1.0 0.0 0.0 0.0 0.0 31.0 84000.0]
 [0.0 1.0 0.0 0.0 0.0 37.823232323232325 45000.0]
 [0.0 0.0 0.0 1.0 0.0 26.0 35000.0]
 [0.0 0.0 1.0 0.0 0.0 48.0 27000.0]
 [0.0 0.0 0.0 0.0 1.0 22.0 70000.0]
 [1.0 0.0 0.0 0.0 0.0 39.0 56180.90452261306]
 [0.0 1.0 0.0 0.0 0.0 57.0 33000.0]
 [0.0 0.0 0.0 1.0 0.0 28.0 62000.0]
 [0.0 0.0 1.0 0.0 0.0 25.0 81000.0]
 [0.0 0.0 0.0 0.0 1.0 37.823

In [20]:
# Encode the Dependent Variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [21]:
print(y)

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1]
