# Data Preprocessing

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
dataset = pd.read_csv('retail_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(X)

[['UK' 22.0 nan]
 ['France' nan 24000.0]
 ['Germany' 24.0 31000.0]
 ['Spain' 28.0 35000.0]
 ['Italy' 21.0 nan]
 ['UK' 32.0 42000.0]
 ['France' 27.0 nan]
 ['Germany' 35.0 52000.0]
 ['Spain' nan 61000.0]
 ['Italy' 29.0 45000.0]
 ['UK' 45.0 68000.0]
 ['France' 52.0 72000.0]
 ['Germany' nan 54000.0]
 ['Spain' 33.0 48000.0]
 ['Italy' 47.0 nan]
 ['UK' 55.0 53000.0]
 ['France' 61.0 45000.0]
 ['Germany' 58.0 nan]
 ['Spain' 49.0 52000.0]
 ['Italy' nan 47000.0]
 ['UK' 26.0 29000.0]
 ['France' 23.0 nan]
 ['Germany' 30.0 40000.0]
 ['Spain' 36.0 51000.0]
 ['Italy' 40.0 nan]
 ['UK' 60.0 48000.0]
 ['France' nan 46000.0]
 ['Germany' 50.0 70000.0]
 ['Spain' 29.0 nan]
 ['Italy' 25.0 33000.0]
 ['UK' 31.0 41000.0]
 ['France' 44.0 58000.0]
 ['Germany' nan 64000.0]
 ['Spain' 57.0 55000.0]
 ['Italy' 62.0 nan]
 ['UK' 20.0 22000.0]
 ['France' 24.0 nan]
 ['Germany' 27.0 36000.0]
 ['Spain' 35.0 50000.0]
 ['Italy' nan 53000.0]
 ['UK' 48.0 62000.0]
 ['France' 55.0 nan]
 ['Germany' 42.0 57000.0]
 ['Spain' 30.0 4200

In [25]:
print(y)

['No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No']


In [26]:
# Taking care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])

In [27]:
print(X)

[['UK' 22.0 46578.94736842105]
 ['France' 39.95302013422819 24000.0]
 ['Germany' 24.0 31000.0]
 ['Spain' 28.0 35000.0]
 ['Italy' 21.0 46578.94736842105]
 ['UK' 32.0 42000.0]
 ['France' 27.0 46578.94736842105]
 ['Germany' 35.0 52000.0]
 ['Spain' 39.95302013422819 61000.0]
 ['Italy' 29.0 45000.0]
 ['UK' 45.0 68000.0]
 ['France' 52.0 72000.0]
 ['Germany' 39.95302013422819 54000.0]
 ['Spain' 33.0 48000.0]
 ['Italy' 47.0 46578.94736842105]
 ['UK' 55.0 53000.0]
 ['France' 61.0 45000.0]
 ['Germany' 58.0 46578.94736842105]
 ['Spain' 49.0 52000.0]
 ['Italy' 39.95302013422819 47000.0]
 ['UK' 26.0 29000.0]
 ['France' 23.0 46578.94736842105]
 ['Germany' 30.0 40000.0]
 ['Spain' 36.0 51000.0]
 ['Italy' 40.0 46578.94736842105]
 ['UK' 60.0 48000.0]
 ['France' 39.95302013422819 46000.0]
 ['Germany' 50.0 70000.0]
 ['Spain' 29.0 46578.94736842105]
 ['Italy' 25.0 33000.0]
 ['UK' 31.0 41000.0]
 ['France' 44.0 58000.0]
 ['Germany' 39.95302013422819 64000.0]
 ['Spain' 57.0 55000.0]
 ['Italy' 62.0 46578.94736

## Encoding Categorical Data

In [28]:
# Encoding the Independent Variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



In [29]:
np.set_printoptions(threshold=np.inf)
print(X)

[[0.0 0.0 0.0 0.0 1.0 22.0 46578.94736842105]
 [1.0 0.0 0.0 0.0 0.0 39.95302013422819 24000.0]
 [0.0 1.0 0.0 0.0 0.0 24.0 31000.0]
 [0.0 0.0 0.0 1.0 0.0 28.0 35000.0]
 [0.0 0.0 1.0 0.0 0.0 21.0 46578.94736842105]
 [0.0 0.0 0.0 0.0 1.0 32.0 42000.0]
 [1.0 0.0 0.0 0.0 0.0 27.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 35.0 52000.0]
 [0.0 0.0 0.0 1.0 0.0 39.95302013422819 61000.0]
 [0.0 0.0 1.0 0.0 0.0 29.0 45000.0]
 [0.0 0.0 0.0 0.0 1.0 45.0 68000.0]
 [1.0 0.0 0.0 0.0 0.0 52.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 39.95302013422819 54000.0]
 [0.0 0.0 0.0 1.0 0.0 33.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 47.0 46578.94736842105]
 [0.0 0.0 0.0 0.0 1.0 55.0 53000.0]
 [1.0 0.0 0.0 0.0 0.0 61.0 45000.0]
 [0.0 1.0 0.0 0.0 0.0 58.0 46578.94736842105]
 [0.0 0.0 0.0 1.0 0.0 49.0 52000.0]
 [0.0 0.0 1.0 0.0 0.0 39.95302013422819 47000.0]
 [0.0 0.0 0.0 0.0 1.0 26.0 29000.0]
 [1.0 0.0 0.0 0.0 0.0 23.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 30.0 40000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 51000.0]
 [0.0 0.0 1.0 0.0 0.0 40

In [30]:
# Encode the Dependent Variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [31]:
print(y)

[0 0 1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1
 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1
 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 0
 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 1
 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0]


## Splitting the Dataset into training set and test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [33]:
print(X_train)

[[0.0 0.0 0.0 0.0 1.0 23.0 28000.0]
 [0.0 0.0 0.0 0.0 1.0 24.0 29000.0]
 [0.0 1.0 0.0 0.0 0.0 42.0 57000.0]
 [0.0 0.0 0.0 1.0 0.0 32.0 43000.0]
 [1.0 0.0 0.0 0.0 0.0 58.0 47000.0]
 [0.0 1.0 0.0 0.0 0.0 39.95302013422819 59000.0]
 [0.0 0.0 0.0 1.0 0.0 46.0 62000.0]
 [0.0 1.0 0.0 0.0 0.0 44.0 60000.0]
 [0.0 0.0 0.0 1.0 0.0 57.0 55000.0]
 [0.0 0.0 1.0 0.0 0.0 50.0 46578.94736842105]
 [0.0 0.0 0.0 0.0 1.0 27.0 31000.0]
 [1.0 0.0 0.0 0.0 0.0 28.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 43.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 50000.0]
 [0.0 1.0 0.0 0.0 0.0 39.95302013422819 54000.0]
 [0.0 0.0 0.0 1.0 0.0 43.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 63.0 46578.94736842105]
 [0.0 0.0 0.0 1.0 0.0 29.0 46578.94736842105]
 [1.0 0.0 0.0 0.0 0.0 26.0 46578.94736842105]
 [0.0 0.0 0.0 0.0 1.0 20.0 23000.0]
 [0.0 0.0 1.0 0.0 0.0 41.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 58.0 46578.94736842105]
 [1.0 0.0 0.0 0.0 0.0 60.0 45000.0]
 [1.0 0.0 0.0 0.0 0.0 40.0 51000.0]
 [0.0 0.0 0.0 1.0 0.0 33.0 48000.0]
 [0.

In [34]:
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 33.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 28.0 38000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 21.0 46578.94736842105]
 [0.0 0.0 0.0 0.0 1.0 28.0 39000.0]
 [1.0 0.0 0.0 0.0 0.0 52.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 39.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 20.0 22000.0]
 [0.0 0.0 1.0 0.0 0.0 41.0 46578.94736842105]
 [0.0 0.0 1.0 0.0 0.0 47.0 46578.94736842105]
 [0.0 0.0 1.0 0.0 0.0 51.0 46578.94736842105]
 [0.0 0.0 0.0 1.0 0.0 31.0 42000.0]
 [0.0 0.0 1.0 0.0 0.0 58.0 46578.94736842105]
 [0.0 0.0 1.0 0.0 0.0 39.95302013422819 47000.0]
 [0.0 0.0 1.0 0.0 0.0 57.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 39.95302013422819 58000.0]
 [0.0 0.0 1.0 0.0 0.0 39.95302013422819 52000.0]
 [1.0 0.0 0.0 0.0 0.0 42.0 53000.0]
 [0.0 0.0 0.0 1.0 0.0 45.0 62000.0]
 [0.0 0.0 1.0 0.0 0.0 30.0 46578.94736842105]
 [0.0 1.0 0.0 0.0 0.0 28.0 38000.0]
 [0.0 0.0 1.0 0.0 0.0 25.0 33000.0]
 [0.0 0.0 1.0 0.0 0.0 39.95302013422819 53000.0]
 [0.0 1.0 0.0 0.0 0.0 24.0 33000.0]
 [0.

In [35]:
print(y_train)

[0 0 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 0
 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0
 1 1 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0
 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 1]


In [36]:
print(y_test)

[0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 1 1 1 0 0 1 1 1]
